/* 🤖 this file was generated by svg-to-ts */

import { TechIcon } from './build/techIcons.model';

export type TechIconNameSubset<
  T extends Readonly<TechIcon[]>
> = T[number]['name'];

export * from './build/techIcon-computer-mouse-solid.icon';
export * from './build/techIcon-computer-solid.icon';
export * from './build/techIcon-hive.icon';
export * from './build/techIcon-memory-solid.icon';
export * from './build/techIcon-microchip-solid.icon';
export * from './build/techIcon-network-wired-solid.icon';
export * from './build/techIcon-server-solid.icon';
export * from './build/techIcon-sim-card-solid.icon';
export * from './build/techIcon-wifi-solid.icon';
export * from './build/complete-icon-set';
export * from './build/techIcons.model';
